### ISSUE TITLE
Masterfile error for Industrial Heat

### ISSUE THREAD

**Issue by rhayward1** [cpmodel/FTT_StandAlone#143]
The master files for FTT-IH are not up to date, so the model cannot run from them and needs to read in the csv files. 
Comments in the code suggest csv files should be taken if no masterfile exists, but an error is returned instead.
Is there still a code which can write/update master files based on the csv files? If so, that would be a big time saver!

**Comment by Femkemilene** [comment]
I'm unaware of code that writes Masterfiles from csv files. What error are you getting? I can think of two:
* Up to about 2 weeks ago, the code only worked for models with a Masterfile. I had accidently broken the functionality of working with csv files only (fixed in this commit: https://github.com/cpmodel/FTT_StandAlone/commit/f288d93adae213e1eb6e761f074e33cbd7f46557)
* It uses the Masterfile to create csv files, but some of the settings in the excel file are wrong, or creates a csv file with a different type of structure, which is not yet covered by input_functions.py.

**Comment by rhayward1** [comment]
The error is due to the model not working with csv files only I believe:

  File "/opt/homebrew/Caskroom/miniforge/base/envs/FTT_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 624, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'FTT-IH-CHI' not found
(FTT_env) rosiehayward@Rosies-Laptop FTT_StandAlone % 

There's some sort of masterfile error. Is there a way I can copy the fix from main over? Thanks, Femke.

**Comment by Femkemilene** [comment]
You can cherry pick a single commit from GitHub Desktop, by going to the branch with the change, to history on the left, and then right click the commit and click cherry pick. 

If that doesn't fix the error, let me know. I don't quite recognize the error message you get, so it may be something new. A work-around may be to remove the masterfiles for now. With the bug fix above, it should then completely rely on csv files.

**Comment by rhayward1** [comment]
I've just checked and I should be up to date with that commit so not sure what the problem is. I've moved the master files into an 'old' folder but now I have a new bug to do with scenarios. I'll try to fix it, thanks, Femke!

**Comment by rhayward1** [comment]
Hi Femke, so the function def generate_model_list(ftt_modules, scenarios) won't work at the moment without a masterfile:

`def generate_model_list(ftt_modules, scenarios):
    """
    Using the models and scenarios from the settings.ini file,
    put these into a dictionary.
    
    Remove the pseudo-scenario gamma, as this should not be initialised separately
    """
    # Remove Gamma pseudo-scenario for initialisation
    scenarios = [item for item in scenarios if item != "Gamma"]
    
    models = {}
    
    for module in ftt_modules:
        module_scenarios = []
        for scenario in scenarios:
            matching_file, file_root = get_masterfile(module, scenario)
            if matching_file:
                # TODO: rewrite this and other code to allow for other types of scenario names
                module_scenarios.append(int(scenario[1:]))
        if module_scenarios:
            models[module] = [module_scenarios, file_root]
    return models`

**Comment by rhayward1** [comment]
I've found the problem. The file FTT_Variables.xlsx is missing in FTT-IH-UPDATE, but it is needed in the latest model version. I'm creating this file which should resolve these issues.
