### ISSUE TITLE
Learning is incorrect in this version of FTT: Power

### ISSUE THREAD

**Issue by rh-camecon** [cpmodel/FTT_StandAlone#20]
See line 725. There should be a dt. Learning is 4 x as powerful as it should be, as investment is scaled to an entire year, not a single quarter. You need to times MEWI by dt.

**Comment by Femkemilene** [comment]
@rh-camecon: did you already check if it's correct in the other sectors / in E3ME-FTT?

**Comment by rh-camecon** [comment]
I think this was just a typo in the most recent FTT Power version, it was incorrect in E3ME-FTT as well. Other sectors do not appear to be affected, at least in my model versions. Hope that helps!

**Comment by Femkemilene** [comment]
It's apparently been wrong since around the FRANTIC work. Versions before 2020 seem to be correct. I'll fix it now in the EEIST version.
