### ISSUE TITLE
Update shares data

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#211]
Update historical generation data to 2022 values using IEA. Consider using IRENA data to update 2023 shares for renewables. See [the update manual](https://github.com/cpmodel/FTT_StandAlone/blob/main/docs/Update%20manuals/FTT-Power%20update%20manual.md) for details on where to find the IRENA dataset. 

Note: the new MWKA implementation in #183 may need to be reverted, as it no longer works as exogenous capacity proper.

**Comment by jp-camecon** [comment]
Progress update:
- New script developed to update using IEA and IRENA data
- IEA data coverage complete to 2022
- IRENA has a new database IRENA_Stat which provides more detail on generation and capacity for fossil fuels as well as renewables. Only capacity goes to 2023 so would have to use MWKA treatment

To do/consider:
- Change processing converters to new classification
- Consider updating load factors 
    -  What is the source for non renewable load factors?
- Consider removing MEWG projection (does this get used for anything? Otherwise it would be good to remove and make clear we only use historical series or if there is a use for it we will need to update this series

**Comment by Femkemilene** [comment]
I do not know/remember what the source is for the fossil load factors. I think it would be good to update these with historical load factors, so that we have a way to judge if load factor projections track historical load factors. Does IEA do capacity as well as generation and can we estimate load factors from that? Otherwise, is IRENA sufficiently detailed for this?

Agree we should remove the MEWG projections. It's a old IEA projection, that J-F used as a comparison case in some old work.

**Comment by jp-camecon** [comment]
So IRENA is probably detailed enough for renewable load factor updates but it does not have full coverage of fossil fuel capacity to be able to make a full assessment for the individual technologies. If we were to use IRENA, we would have to make some assumptions of how we adjust the relative load factors for coal oil and gas from averages.

Good we can clean out the MEWG projections in the new version of the workbook then.

**Comment by jp-camecon** [comment]
So to update, I have found another dataset EMBER [https://ember-climate.org/data-catalogue/yearly-electricity-data/](url) which gives estimates of coal and gas capacity and generation which allows us to fill in most gaps in load factors from IRENA. 

I will update the full methodology shortly but we now have generations and load factors up to 2022 and capacity for renewables in 2023 as MWKA. All prepared by a single python script.

Now depending on the progress on cost data, I can process this on the new or old technology classification

**Comment by Femkemilene** [comment]
That's great, another open-access dataset! (I found out yesterday that OECD is open-access since July. They have information on electricity prices among other indices.)

In terms of the cost update: Zoé will be back from holiday on Monday, so I've asked for a meeting Tuesday. I've made a start myself, and have BNEF data in the right format with a script. My hope is for an end-of-September finish, as I'd like to integrate the entire update in the tipping point cascade paper.

As far as I understand, @Sahastrabuddhe, ***@***.***> is almost finished with rejigging the files for the new format. I think even without the cost update we can use the new classification if we proxy some of the new technologies.

Femke
________________________________
