### ISSUE TITLE
Find learning rates in storage technology

### ISSUE THREAD

**Issue by rishids01** [cpmodel/FTT_StandAlone#226]
We need to find learning rates from literature for three technologies. Hydrogen, CAES, Lithium-ion.

**Comment by rishids01** [comment]
Updated Pumped hydro, Marine, Hydrogen and Li-ion learning rates.

**Comment by Femkemilene** [comment]
@rishids01: could you document the learning rate sources here?

**Comment by rishids01** [comment]
Li-ion - https://www.cell.com/joule/fulltext/S2542-4351(22)00410-X?fbclid=
Pumped Hydro - https://www.sciencedirect.com/science/article/pii/S2542435120301252
Hydrogen - https://www.cell.com/joule/fulltext/S2542-4351(21)00306-8#mmc1
Marine - https://www.sciencedirect.com/science/article/pii/S0040162513003041
