### ISSUE TITLE
Unable to run model on MAC

### ISSUE THREAD

**Issue by jk694exe** [cpmodel/FTT_StandAlone#40]
Attached the error file when running the FTT model on Mac
[error_macJK (1).docx](https://github.com/cpmodel/FTT_StandAlone/files/11960024/error_macJK.1.docx)

**Comment by ldxib2** [comment]
Further in person investigation:
- All file paths in backend changed to be mac friendly and reinstallation on local drives of both model and python but still encountering errors 
- run_file.cmd works and produces output so problem seems to be integration with frontend
