### ISSUE TITLE
FTT-Tr, FTT-H missing from frontend results

### ISSUE THREAD

**Issue by cormacmlynch** [cpmodel/FTT_StandAlone#72]
A few of the FTT models (including transport and heat) are missing from the results section of the frontend. Our understanding is that the files to fix this are not included in the github repo.

**Comment by CamEconJP** [comment]
The missing files have now been added to the main branch. Note that what is viewable in the frontend is determined by utilities/titles/variable_listing.xlsx. To show in the frontend, this needs to be converted to a json file by running "Manager_new\Update manager metadata.py"

In particular the fields Summary and Detailed correspond to the results page options of Simple and Detail. If a Y is not marked for certain variables then they will not show in these views. You can always see all variable by selecting "All"
