### ISSUE TITLE
Ensure output is saved when running from run_file

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#81]
Currently, if you run the model not from the front-end, the output does not get saved in a pickle file. Easier if it were.

**Comment by pv-camecon** [comment]
We could probably steal the code from the back end. Something like this:

```    scenarios_log = {}
    for scenario in scenarios:

        # Update scenario log
        scenarios_log[scenario] = {}
        scenarios_log[scenario]['run'] = datetime.datetime.timestamp(datetime.datetime.now())
        scenarios_log[scenario]['description'] = "Test Scenario, provided by Cambridge Econometrics"
        scenarios_log[scenario]['years'] = [str(x) for x in model.timeline]
        print(scenarios_log)

    # Save output for all scenarios to pickle
    #TODO Setup way to retain older results?
    results =  model.output
    os.makedirs(os.path.dirname(f"{rootdir}\\Output\\"), exist_ok=True)     # Create Output folder if it doesn't exist
    with open('Output\Results.pickle', 'wb') as f:
        pickle.dump(results, f)
    # Save metadata on current model run
    with open("{}\\Output\\Scenarios.json".format(rootdir), 'w') as f:
        json.dump(scenarios_log, f)`

**Comment by ldxib2** [comment]
I also wrote a script that could go into the support folder that also allows you to select core variables if you want to save space. We could combine it with the above if desired

![image](https://github.com/cpmodel/FTT_StandAlone/assets/57045971/4bc689a0-9040-4e31-91d6-56b5bebace91)

**Comment by ldxib2** [comment]
@pv-camecon, we are having some trouble calibrating the Gamma values for the FTT-P update through the frontend. The issue seems to be that there is not Output/Gamma.pickle file which the front end is trying to load in line 974 of FTT_backend.py. Could this be down to the fact that gamma output is also not being saved like the main ouput?
