### ISSUE TITLE
Change classification

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#84]
In the recent update of FTT:P, it became clear that BIGCC (Biomass-based integrated gasification combined cycle) and fuel cells lack data, and are not taking off. 

I believe our calculations are O(N) to O(N**2), so removing three technologies may speed up the code by 10-25%. We can do this in our current Python update, but we need some capacity to do this in the FORTRAN version as well. Opening up this issue to ask if there are any objections to this? Or if we require a deeper rethinking of our classification.

**Comment by Femkemilene** [comment]
Had a chat with JF on the topic. The original classification was based on the IEA´s projected cost of electricity production. As the IEA no longer provides information for BIGCC, I don´t see any reason to keep the technology, as it complicates updating the standard solid biomass technology. Fuel cells are still mentioned, but it is unclear what technology they represent, so I would like to still remove this one.

**Comment by pv-camecon** [comment]
Alright, agreed on (B)IGCC given that we don't have specific data for them (generation nor costs). However, after thinking a little bit I'd argue to keep (presumably stationary) fuel cells in the list. While an unlikely candidate for future power systems, there are a few nations focussed on fuel cells. We'd therefore need to be able to represent them in some of our work.

**Comment by Femkemilene** [comment]
Another one we may wish to remove is IGCC (integrated gasification combined cycle). The 2020 IEA cost data no longer have this a separate category. This gives us some space to include storage technologies or wind+storage/solar+storage into the model. The IGCC data is based on older data, and we do not have any shares data for the technology.

**Comment by Femkemilene** [comment]
Decision: we remove four technologies from the list: the two BIGCC and the two IGCC ones. I've made a script that deletes these technologies from the sheets which have a country x technology format (such as BCET). It's in the linked branch. This means that
* We need to manually remove it from the other sheets
* We need to go over the code systematically to adjust indexes where stuff is hardcoded (mostly in rldc).

**Comment by Femkemilene** [comment]
The current proposed classification is. For backward compatability of some of the scripts, I've kept onshore/offshore/solar PV in the same indices. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/WORKPR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/WORKPR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Nuclear |  
-- | --
Oil |  
Coal |  
Coal + CCS |  
Waste |  
Waste + CCS |  
CCGT | Empty shares initially?
CCGT + CCS | Empty shares initially?
OCGT |  
OCGT + CCS |  
Biomass |  
Biomass + CCS |  
Large Hydro | USE IRENA for breakdown
Pumped hydro | Use IRENA for breakdown
Geothermal |  
Marine |  
Onshore | Use IRENA for breakdown
Offshore | Use IRENA for breakdown
Solar PV |  
CSP |  
Fuel cells / turbines | Empty shares initially
Lithium-ion | Empty shares initially
CAES | Empty shares initially



</body>

</html>

**Comment by jp-camecon** [comment]
Just to check that for CCGT vs OCGT, you mean OCGT would be empty shares not CCGT?

**Comment by Femkemilene** [comment]
Yes, corrected above.

**Comment by jp-camecon** [comment]
I have checked in with other CE model users and they raise no concerns with the new classification. As such we have a greenlight from CE to go ahead with the new classification changes
