### ISSUE TITLE
Front end not working on Windows 11

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#93]
The front end displays a localhost:5000 not found error. No other error message can be found.

**Comment by pv-camecon** [comment]
I just tried it on my laptop with Windows 11. If you clear your cache and launch from the command prompt, then it should work. This will probably happen every time the manager gets updated (because of new variables, models, etc.).

**Comment by Femkemilene** [comment]
Good to know it's not a Windows 11 issue. Clearing my cache didn't resolve it. I imagine that a manager update would break further down the line (showing incorrect titles), not at the first load screen.

I can imagine it has something to do with the absence of admin privileges on this laptop, or possibly the security issues that GitHub flags. I'll open a ticket with the university IT, even though that'll likely take a few months before it's resolved..
