### ISSUE TITLE
FTT-Tr EV shares too high in some regions

### ISSUE THREAD

**Issue by cormacmlynch** [cpmodel/FTT_StandAlone#99]
The shares of EVs in some regions including India and the US are too high in the Python FTT-Tr compared with the Matlab version. Costs and other assumptions appear to be okay. More regions could be affected by this.

Things to investigate:
1. Impact of gamma values
2. Euler forward vs. RK4
3. Potential time-step issues

**Comment by pv-camecon** [comment]
RK4 will definitely have an impact. From how @rhayward1 explained it, if there is a lot of curvature in the uptake profile, then you will see larger differences in the outcome when comparing RK4 to Euler. My guess is that EV uptake show a lot of curvature. 

Recalibration should hopefully fix the issue somewhat.

Alternatively, you could try implementing the RK4 in the Matlab environment.

**Comment by Femkemilene** [comment]
@aileenlam28: would you have time to implement RK4 in Matlab at some point? As we're unable to run the Matlab model ourselves, it's quite difficult for us to resolve the remaining differences between the models.
